// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFaAp-G5oKsfFB8eicPhyTVsS2M15HrlA',
    appId: '1:849341046941:web:800de74658afa8bc367474',
    messagingSenderId: '849341046941',
    projectId: 'jadran-bec39',
    authDomain: 'jadran-bec39.firebaseapp.com',
    storageBucket: 'jadran-bec39.appspot.com',
    measurementId: 'G-YNLXJDPYD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWEhYbeLG39ghr-hi009UBDPwNdID3Z8',
    appId: '1:849341046941:android:c1eb1b70c94ea11b367474',
    messagingSenderId: '849341046941',
    projectId: 'jadran-bec39',
    storageBucket: 'jadran-bec39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNIaHP4BH3zOHcRWiPCgc2EvvOLVa_do',
    appId: '1:849341046941:ios:5eb253ee00d25b81367474',
    messagingSenderId: '849341046941',
    projectId: 'jadran-bec39',
    storageBucket: 'jadran-bec39.appspot.com',
    iosBundleId: 'com.example.jadran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfNIaHP4BH3zOHcRWiPCgc2EvvOLVa_do',
    appId: '1:849341046941:ios:e66e8af9ab4a3ebb367474',
    messagingSenderId: '849341046941',
    projectId: 'jadran-bec39',
    storageBucket: 'jadran-bec39.appspot.com',
    iosBundleId: 'com.example.jadran.RunnerTests',
  );
}
